caddyserver/ingress

internal/caddy/convert.go

Signed-off-by: Marco Vito Moscaritolo <mavimo@gmail.com>
The port for the backend service is not specified so we had issue on network resolving generating error 500
```log
2019/11/10 15:19:03.084    ERROR    http.log.error    making dial info: upstream apple-service.default.svc.cluster.local: invalid dial address apple-service.default.svc.cluster.local: address apple-service.default.svc.cluster.local: missing port in address    {"request": {"method": "HEAD", "uri": "/apple", "proto": "HTTP/1.1", "remote_addr": "10.244.1.1:59740", "host": "172.17.255.1", "headers": {"User-Agent": ["curl/7.58.0"], "Accept": ["*/*"]}}}
```
this patch will expose the service using cluster host name including port number so we can make it work internally:
```log
2019/11/10 15:23:53.334    INFO …
```

Specify the ingress service port for internal hostname

---

Dockerfile

You can (and should) use Docker to build GO programs. With this updated `Dockerfile` you can build the binary with one simple command `docker build -t your-image-name:tag .`, then push it to your favorite registry and use it in the Helm chart.

Build GO binary inside Docker

---

README.md

add the missing backslash in the helm install cmd  of README.md.
BTW , as there's no released version , actually the install cmd does not works (it seems helm ignores the alpha/beta/rc version by default),
should we add  `--devel` flag  temporarily to make it works until there is a released version?
just like 
```
helm install \
--namespace=caddy-system \
--repo https://caddyserver.github.io/ingress/ \
--atomic \
--set image.tag=latest \
--devel \
mycaddy \
caddy-ingress-controller
```

docs: add the missing backslash

---

pkg/storage/storage.go

This PR fixes a bug that prevented a certificate to be updated (if outdated for example).

Allow storage adapter to overwrite a secret

---

charts/caddy-ingress-controller/Chart.yaml
charts/caddy-ingress-controller/templates/configmap.yaml
charts/caddy-ingress-controller/templates/deployment.yaml
charts/caddy-ingress-controller/values.schema.json
charts/caddy-ingress-controller/values.yaml
cmd/caddy/flag.go
cmd/caddy/main.go
go.mod
go.sum
internal/caddy/config.go
internal/controller/action.go
internal/controller/configmap.go
internal/controller/controller.go
internal/store/store.go
kubernetes/sample/example-configmap.yaml

This PR change the way caddy options are read from CLI flags to a specific ConfigMap in the caddy NS.
For now, there are only 2 flags you can pass to caddy:
- `namespace`: Namespace to watch for ingress resources
- `configmap-name`: Name of the configmap to use as global options
In the ConfigMap, 3 fields are supported for now (more will be added soon), inspired by [Caddy global options](https://caddyserver.com/docs/caddyfile/options#global-options):
- `debug` Set log level to debug
- `acmeCA`: Change the acme url (e.g. LE staging)
- `email`: Email used for TLS
**Notes**
- I didn't update charts for now bc of #31.
Fixes #11

Use ConfigMap for Global Options

---

.github/workflows/helmchart-release.yml

It seems helm has renamed their HEAD from master to main. Update the
github workflow to reflect that.
Fixes #69

Use main branch for helm/chart-releaser-action

---

.github/workflows/helmchart-release.yml
.github/workflows/main.yml
CONTRIBUTING.md
charts/caddy-ingress-controller/Chart.yaml
charts/caddy-ingress-controller/values.yaml
ct.yaml

Updated some actions and improve release workflow. New workflow would work like this:
- Release new app version (e.g. `v0.1.1`)
- Create PR to bump app version in helm chart which also bump chart version 
- Update the chart version in the PR that change the chart

Fix chart test CI

---

charts/caddy-ingress-controller/templates/poddisruptionbudget.yaml

The policy/v1beta version is deprecated and being phased out.

Move policy api version to stable API version

---

README.md
charts/caddy-ingress-controller/Chart.yaml
kubernetes/sample/example-ingress.yaml

Helm discard <1.0.0 versions so I bumped the chart version to 1.0.0 (not the app version).
Fixes #79 
Fixes #78 
Fixes #77 
Fixes #71
Fixes #73 
Fixes #43

Release v1.0.0 of caddy-ingress-controller chart

---

pkg/storage/storage.go

Certmagic expects fs.ErrNotExist when the Private Key cannot be found, else it assumes some other error happened. So if there is no existing private key, this will fail and no new key will be generated.
This PR uses the apimachinery errors package to check for a notFound error and returns the correct error to certmagic so a new private key can be created.

If secret doesn't exist, return fs.ErrNotExist

---

charts/caddy-ingress-controller/README.md
charts/caddy-ingress-controller/values.schema.json
charts/caddy-ingress-controller/values.yaml
internal/caddy/global/configmap.go
pkg/store/configmap_parser.go

To configure ZeroSSL as the Acme CA, I needed the EAB config options exposed.

Add EAB Config options

---

internal/caddy/ingress/annotations.go
internal/caddy/ingress/reverseproxy.go

Useful if your backend application is using HTTPS (For example Unifi Network Controller). Often these apps use self-signed certificates, so caddy needs to ignore that fact.
The two annotations add the respective feature to caddy with the defaults behaving similar to nginx.

Add Backend Protocol & skip verify annotation

---

charts/caddy-ingress-controller/templates/loadbalancer.yaml
charts/caddy-ingress-controller/values.yaml

This is for both issue #110 and #109 
I left some of the more common annotations required for an AWS NLB as comments. It's not as good as instructions, but it should help some people who have no idea what to put in that section.
I updated my project with this template and these additions to the values.yaml. Everything appears to be functioning as it should (the LoadbBalancerIP section is blank for me because I'm linking AWS EIPs).

Added LoadBalancer annotations and LoadBalancerIP

---

internal/k8s/pod.go

Some services in Kubernetes can have a ClusterIP with the string "None", indicating that it is a virtual service.
For more details, see https://kubernetes.io/docs/concepts/services-networking/service/#headless-services.
This PR ensures that Caddy does not set "None" as the hostname inside the Ingress LB status.

Take into account that the ClusterIP can be "None"

---

.github/workflows/release-controller.yml

This pull request adds a job in `release-controller.yml` which should automatically change `appVersion` in `Charts.yml` and `image.tag` in `values.yaml` (both located in `charts/caddy-ingress-controller`).
The idea behind this is as such: When developers make changes to the controller, we release a new version. However, we don't necessarily release new versions of our charts. This changes our flow to make it easier to roll out changes in charts easier. The flow typically will look like this if this is landed:
```mermaid
graph TD
A[Create a new release/tag]
B[Workflow triggered by tag event]
A-->B
C[Package controller with GoReleaser]
D[Update Chart.yml and values.yml]
E[Create pull request]
B-->C
B-->D
D-->E
```
**Note**: We could even update `version ` in `Charts.yml` with a patch …

chore(workflow): bump charts automatically when controller is released

---

pkg/store/configmap_parser.go

Fix #121 
ConfigMap parser didn't match the public config fields.

fix: OnDemand ratelimit config isn't handled properly

---

.goreleaser.yaml

Previously, with goarch not set, all "arm64" builds on Dockerhub actually contained an amd64 binary, preventing the ingress controller from running on arm64.

fix: Set goarch

---

.github/workflows/main.yml
.github/workflows/release-controller.yml

- Bump the Go version used in CI from 1.18 to 1.20

ci: update Go version used in CI

---

.github/workflows/main.yml
.github/workflows/release-controller.yml
go.mod

- Update to go 1.21
- Force CI to use the last minor version available (to keep consistency with what caddy is doing [here](https://github.com/caddyserver/caddy/blob/master/.github/workflows/ci.yml#L63))

Update to go 1.21 and always use latest version

---

.github/dependabot.yml

- Enable dependabot for Go deps

chore: enable dependabot for go packages

---

.github/workflows/main.yml
cmd/caddy/main.go
internal/caddy/convert_test.go
internal/caddy/global/healthz.go
internal/caddy/global/ingress.go
internal/caddy/global/ingress_sort.go
internal/caddy/global/ingress_sort_test.go
internal/caddy/global/metrics.go
internal/caddy/global/tls.go
internal/controller/action_ingress.go
internal/controller/action_status.go
internal/controller/action_tls.go
internal/controller/controller.go
internal/k8s/ingress.go
internal/k8s/pod.go
internal/k8s/tls_secret.go
pkg/converter/converter.go
pkg/proxy/proxy.go

- Minor changes in formatting (automated)

chore: minor formatting improvements

---

.github/workflows/release-chart.yml

- Remove `mark_as_latest` parameter that is not supported from the chart-release action, see [here](https://github.com/helm/chart-releaser-action/blob/v1/action.yml)

fix: remove parameter that is not supported in the chart-release action

---

internal/caddy/global/tls.go
internal/caddy/global/tls_test.go

During the code review for the contribution #133 when added test we notice that we register the same domain multiple time, this PR add test to cover the TLS plugin and fix the underground problem.

fix: remove multiple registered domain for TLS managed certificates

---

cmd/caddy/main.go

- Rename internal constant name to better represent the value

chore: use a better name for internal const

---

charts/caddy-ingress-controller/templates/loadbalancer.yaml
charts/caddy-ingress-controller/values.yaml

Hello Caddy team!
It is often desirable to preserve the client IP when using an ingress controller. However, to achieve this, the LoadBalancer `externalTrafficPolicy` need to be set to `Local` (see references at end of PR).
This PR proposes this: exposing the `externalTrafficPolicy` in the values.
**References**
- https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip
- https://learn.microsoft.com/en-us/azure/aks/load-balancer-standard#maintain-the-clients-ip-on-inbound-connections

feat: exposing loadBalancer.externalTrafficPolicy value

---

.goreleaser.yaml

fix(ci): fix gorelease tagging parameters

---

charts/caddy-ingress-controller/Chart.yaml
charts/caddy-ingress-controller/values.yaml

- Bump the ingress controller version in the chart (pending `caddy/ingress:v0.2.1` release)

feat(chart): bump caddy ingress controller version

---

.goreleaser.yaml

- Include missing `v` prefix in docker image manifest for major and minor tags

fix: docker image manifest should include 'v' prefix

---

.github/workflows/main.yml
.github/workflows/release-chart.yml

This is a PR to propose to move the default branch to `main` as GH propose for new repos:
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-branches#about-the-default-branch

chore: rename default branch to 'main'

---

internal/controller/action_tls.go

Replace the `ioutil.WriteFile` deprecated function, see https://pkg.go.dev/io/ioutil#WriteFile for more details.

chore: replace depreacted function ioutil.WriteFile with os.WriteFile

---

internal/controller/controller.go
pkg/proxy/proxy.go

Also deprecated the one we have as it's redundant with the one included in caddy and people should use the one provided by caddy.
Because it's the same library behind, I do not expect any breaking change.
I'll let it in draft until the new proxyprotol module is merged and released in caddy (https://github.com/caddyserver/caddy/pull/5915)

feat: Use caddy's internal Proxy protocol module

---

charts/caddy-ingress-controller/templates/loadbalancer.yaml
charts/caddy-ingress-controller/templates/service.yaml
charts/caddy-ingress-controller/values.schema.json
charts/caddy-ingress-controller/values.yaml

What problem:
I need to install caddy to K8s, but I don't need external load balancer.
Why this is a solution:
By adding this `loadBalancer.enabled` value, which default to true, we can make the load balancer optional. This is also to ensure smart transition to `service.yaml` for already-existing user of this helm chart.

feat(chart): add service.yaml

---

cmd/caddy/main.go
internal/caddy/convert_test.go
internal/caddy/global/secrets_store.go
internal/caddy/global/tls.go
internal/caddy/global/tls_test.go
internal/controller/action_tls.go
internal/controller/controller.go
internal/k8s/pod.go
pkg/storage/storage.go
pkg/store/store.go
pkg/store/store_test.go

These are some changes I made to run the controller outside of the cluster:
- Uses `KUBECONFIG` if set. Ideally, we'd also support `-kubeconfig`, because the messages logged by `BuildConfigFromFlags` allude to this.
- Allow specifying a namespace for the ConfigMap (e.g. `-config-map foo/bar`). If set, Secrets will then also be generated in this namespace, rather than the pod namespace.
- Make the `POD_{NAMESPACE,NAME}` vars optional and warn if not set. If not set, `-config-map` must be provided with an explicit namespace, and Ingress status will not list external IPs.
- Prefers `$RUNTIME_DIRECTORY/certs` over `/etc/caddy/certs`, if the env var is set. This is a variable set by systemd when setting `RuntimeDirectory` in the service configuration.
Though I wonder if we should not just use …

Allow running outside a cluster
